baseurl      = "localhost"
title        = "#MSOSSCDA"
languageCode = "en-us"
theme        = "hugo-theme-hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "The open source cloud developer advocates at Microsoft"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "light"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "#MSOSSCDA"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "OSS CDAs"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"


# top-level menu items
[[menu.main]]
    identifier = "who"
    name = "Who We Are"
    url = "/who"
[[menu.main]]
    identifier = "writing"
    name       = "Writing"
    url        = "/posts"
[[menu.main]]
    identifier = "projects"
    name = "Our Projects"
    url = "/projects"

